plugins:
  discourse_table_gallery_enabled:
    default: true
    client: true
  table_gallery_categories:
    default: ""
    type: list
    list_type: category
    client: true
  table_gallery_hidden_tags:
    default: ""
    type: list
    client: true
